name: Main Pipeline

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: echo "Building..."

  docker:
    needs: build
    name: Build docker image
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit

  trivy:
    needs: build
    name: Build trivy scan
    uses: ./.github/workflows/trivy.yml
    secrets: inherit

  SlScan:
    needs: build
    name: Build SL scan
    uses: ./.github/workflows/shiftleft-analysis.yml
    secrets: inherit
