name: Policy as Code

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  security-events: read
  contents: read
  pull-requests: write

jobs:
  policy-as-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Advance Security Policy as Code
      uses: advanced-security/policy-as-code@v2.8.0
      with:
        rules: |
          - id: critical-code-scanning-alerts
            description: "Fail the build if there are any critical code scanning alerts."
            severity: critical
            type: code-scanning-alerts
        fail-on-violation: false
      env:
        GITHUB_TOKEN: ${{ secrets.HACKER }}
