name: SL Scan

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: write-all

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        type: "credscan,javascript-typescript"
        output: reports.sarif
      env:
        WORKSPACE: ./ 
        GITHUB_TOKEN: ${{ secrets.HACKER }}
        SCAN_AUTO_BUILD: true
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports.sarif

