name: workflow for Maven using Snyk security scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_KEY }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        run: cat snyk.sarif
      
