name: Trivy Scan

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]

permissions: write-all

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.HACKER }}

    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/download/v0.30.0/trivy_0.30.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.30.0_Linux-64bit.deb

    - name: Pull Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        docker pull $IMAGE_ID:test

    - name: Scan Docker image for vulnerabilities
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        trivy image --severity LOW,MEDIUM,HIGH,CRITICAL $IMAGE_ID:test --format sarif --output trivy-report.sarif

    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
         sarif_file: trivy-report.sarif
    # - name: Upload Trivy scan report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: trivy-scan-report
    #     path: trivy-report.json

    # - name: Download Trivy scan report
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: trivy-scan-report
    #     path: ./trivy-scan-report

    # - name: Display scan report
    #   run: |
    #     cat ./trivy-scan-report/trivy-report.json
